### ISSUE TITLE
Specify node version in workflow files.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/distributor#928]
### Is your enhancement related to a problem? Please describe.

In b04cc5db910251b66f9e1e3eb857f3eafa0119a1 an `.nvmrc` file was added to specify the version of node required for the repo.

Follow up this work by specifying the workflow files use the version of node specified in this file:

```yaml
            - name: Use desired version of NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
```

Support for these files was added in version 2.5 of the action so that will need to be updated where applicable. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
